# Generated by Django 4.2.6 on 2023-10-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='davomiylogi',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='fasl',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='homiy',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='iframe_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='janr',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='kompaniya',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='ovozberishaktorlari',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='qism',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='rejesyor',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='tili',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='yili',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='yoshcheklovi',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('iframe_content', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
