# Generated by Django 4.2.6 on 2023-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_davomiylogi_movie_fasl_movie_homiy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='davlat',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
