# Generated by Django 4.2.6 on 2023-10-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='homiy',
            new_name='puldor_homiy',
        ),
    ]
