# Generated by Django 4.2.6 on 2023-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_rename_homiy_movie_puldor_homiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='yoshkategoryasi',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
